name: Azure Bicep

on: [push]
# on: [workflow_dispatch]

env:
  AZURE_DEPLOYMENT_NAME: "vickk73test"
  AZURE_RESOURCEGROUP_NAME: "vickk73testrg"
  # AZURE_RESOURCEGROUP_NAME: "{{ env.AZURE_DEPLOYMENT_NAME }}rg"
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_GUID }}
  AZURE_DEPLOYMENT_REGION: "australiaeast"
  # AZURE_DEPLOYMENT_REGION: "australiasoutheast"
  # AZURE_DEPLOYMENT_REGION: "centralus"

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@main
    
    - name: Run Bicep linter
      run: az bicep build --file ./main.bicep

  validate: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@main
    
    - name: Run Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true
  
    - name: Run preflight validation
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./main.bicep
        deploymentMode: Validate
  
  # preview:
  #   runs-on: ubuntu-latest
  #   needs: [lint, validate]
  #   steps:
  #   - name: Checkout GitHub Action
  #     uses: actions/checkout@main
    
  #   - name: Run Azure Login
  #     uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}
  #       allow-no-subscriptions: true
    
  #   - name: Run what-if
  #     uses: azure/arm-deploy@v1
  #     with:
  #       failOnStdErr: false
  #       resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
  #       template: deploy/main.bicep
  #       additionalArguments: --what-if

  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout GitHub Action
  #     uses: actions/checkout@main
   
  #   - name: Run Azure Login
  #     uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}
  #       allow-no-subscriptions: true

  #   - name: Run Azure Bicep Deploy
  #     uses: azure/CLI@v1
  #     with:
  #       inlineScript: |
  #         az account set --subscription ${{ env.AZURE_SUBSCRIPTION }}
  #         az deployment sub create -f ./main.bicep -n ${{ env.AZURE_DEPLOYMENT_NAME }} -l ${{ env.AZURE_DEPLOYMENT_REGION }} -p token=${{ secrets.GIT_HUB_CREDENTIALS }} password=${{ secrets.ADMIN_CREDENTIALS }}